DLS-7728 add update-change registered details page
hmrc/soft-drinks-industry-levy-variations-frontend pull request #102
Opened 2023-08-08 14:34 UTC by GinnyThomas

UI page: https://github.com/hmrc/soft-drinks-industry-levy-ui-tests/pull/154#issue-1841460250
![Screenshot 2023-08-08 at 14 37 44](https://github.com/hmrc/soft-drinks-industry-levy-variations-frontend/assets/90277886/c33321e2-d5c3-4272-b718-885eeaa8f686)
![Screenshot 2023-08-08 at 14 37 38](https://github.com/hmrc/soft-drinks-industry-levy-variations-frontend/assets/90277886/080d7c71-1ce6-4994-93d6-d04969b24eef)
![Screenshot 2023-08-08 at 14 36 11](https://github.com/hmrc/soft-drinks-industry-levy-variations-frontend/assets/90277886/48d8a78b-25e3-4387-af8d-1205f9346ca2)

2023-08-09 09:16 UTC, ChrisHillCap requested changes
couple of comments, looks pretty swish apart from those

2023-08-09 09:16 UTC, ChrisHillCap commented on app/forms/updateRegisteredDetails/ChangeRegisteredDetailsFormProvider.scala
> +  def apply(): Form[Set[ChangeRegisteredDetails]] =
I think we need some form validation to check the isVoluntary flag as I think (its hard to read) the old code validated in the form
i..e
-  when im voluntary, i am allowed these checkboxes
- when im not voluntary, im not allowed to submit x checkbox

(taken from L300 in Variations journey in old fe
  ```  import ContactChangeType._
    val changeOptions =
      if (data.isVoluntary)
        ContactChangeType.values.filter(_ != ContactChangeType.Sites)
      else
        ContactChangeType.values

    for {
      change <- ask[Set[ContactChangeType]](
                 "change-registered-details",
                 validation = Rule.nonEmpty[Set[ContactChangeType]] alongWith Subset(changeOptions: _*)
               )```

2023-08-09 09:16 UTC, ChrisHillCap commented on it/controllers/updateRegisteredDetails/ChangeRegisteredDetailsControllerISpec.scala
> +  "GET " + normalRoutePath - {
can we check which checkboxes appear based on the "voluntary" flag for the GET AND POST(400) in the it tests

2023-08-10 08:49 UTC, hmrc-web-operations commented
Thank you for submitting a pull request on this HMRC repository. A member of the HMRC team will review your changes and action accordingly.

HMRC reviewer: please reference [this runbook](https://github.com/hmrc/build-and-deploy/blob/main/runbooks/reviewing_external_pull_requests.md) for guidance on how to proceed.

2023-08-11 08:10 UTC, ChrisHillCap approved these changes

2023-08-11 08:10 UTC, ChrisHillCap commented
lgtm

2023-08-11 10:14 UTC, GinnyThomas commented
Updates made per request - had difficulty with verified signature, new branch created as files were inadvertently lost.

2023-08-11 10:14 UTC, closed without merging