DLS-8893: Create Required User Answers - Change Business Activity
hmrc/soft-drinks-industry-levy-variations-frontend pull request #134
Opened 2023-09-28 08:28 UTC by drewmiley

2023-10-10 09:25 UTC, GinnyThomas requested changes

2023-10-10 09:25 UTC, GinnyThomas commented on test/controllers/actions/RequiredUserAnswersForChangeActivitySpec.scala
> +//    s"should return 1 item on the missing answer list when user changes a $StartDatePage required answer from CYA, " +
please remove unneeded code

2023-10-10 09:25 UTC, GinnyThomas commented on app/controllers/actions/RequiredUserAnswersForChangeActivity.scala
> +      pagesRequiredForPackAtBusinessAddressPage.map(RequiredPage(PackAtBusinessAddressPage, _)(implicitBoolean)),
see note below regarding pack at business address page

2023-10-10 09:25 UTC, GinnyThomas commented on app/controllers/actions/RequiredUserAnswersForChangeActivity.scala
> +}
warehouse details page??

2023-10-12 10:11 UTC, drewmiley commented on test/controllers/actions/RequiredUserAnswersForChangeActivitySpec.scala
> +//    s"should return 1 item on the missing answer list when user changes a $StartDatePage required answer from CYA, " +
Done

2023-10-12 13:29 UTC, drewmiley commented on test/controllers/actions/RequiredUserAnswersForChangeActivitySpec.scala
> +        )
I think this is valid as whether or not these are required will depend on the AmountProduced, and ContractPacking pages. So when they are missing, then we cannot yet say the others are.

2023-10-12 13:39 UTC, drewmiley commented on test/controllers/actions/RequiredUserAnswersForChangeActivitySpec.scala
> +            .set(PackAtBusinessAddressPage, true).success.value
Should be fixed

2023-10-12 13:56 UTC, drewmiley commented on test/controllers/actions/RequiredUserAnswersForChangeActivitySpec.scala
> +            .set(PackAtBusinessAddressPage, true).success.value
This is for all journeys - regardless of whether they are coming from CYA? In this case, I may put the guard on the PackAtBusinessAddress controller

2023-10-12 14:08 UTC, drewmiley commented
WIP - Need to fix RequiredUserAnswers unit tests, and add redirect guard to PackAtBusinessAddress

2023-10-16 13:06 UTC, GinnyThomas approved these changes

2023-10-16 13:06 UTC, merged