DLS-9020: Ensure ALF does Not Change user from Change to Normal Mode
hmrc/soft-drinks-industry-levy-variations-frontend pull request #157
Opened 2023-10-23 14:03 UTC by drewmiley

2023-10-24 12:42 UTC, GinnyThomas requested changes
Please add
GET        /change-secondary-warehouse-details
POST       /change-secondary-warehouse-details
to the app routes for update business activity.

2023-10-24 14:18 UTC, GinnyThomas approved these changes

2023-10-24 15:44 UTC, drewmiley commented
Need to investigate
GET        /business-address                                controllers.updateRegisteredDetails.BusinessAddressController.onPageLoad()
GET        /change-business-address                         controllers.updateRegisteredDetails.BusinessAddressController.changeAddress()
POST       /business-address                                controllers.updateRegisteredDetails.BusinessAddressController.onSubmit()
also, and whether CheckMode needs to be implemented for this

2023-10-25 15:23 UTC, GinnyThomas approved these changes

2023-10-25 15:31 UTC, merged