Dls 8445 create packaging site details
hmrc/soft-drinks-industry-levy-variations-frontend pull request #87
Opened 2023-07-28 13:49 UTC by ginnyamazed

![Screenshot 2023-07-27 at 13 48 45](https://github.com/hmrc/soft-drinks-industry-levy-variations-frontend/assets/90277886/150ce180-6588-4f02-a255-b43ec6c44705)
![Screenshot 2023-07-27 at 13 49 05](https://github.com/hmrc/soft-drinks-industry-levy-variations-frontend/assets/90277886/ac51d53b-e6aa-4cc9-9655-1fe77941ec3a)
![Screenshot 2023-07-27 at 13 50 30](https://github.com/hmrc/soft-drinks-industry-levy-variations-frontend/assets/90277886/d36717f0-2fc6-4b6a-9de0-2956cd282e0d)

2023-07-28 14:08 UTC, ginnyamazed commented
UI page addition, https://github.com/hmrc/soft-drinks-industry-levy-ui-tests/pull/143#issue-1826426587

2023-07-31 09:49 UTC, RaminEsfandiari commented
Not part of this change but I noticed you had a duplicate route in cancel registration. Could you remove that either as part of this PR?
![image](https://github.com/hmrc/soft-drinks-industry-levy-variations-frontend/assets/5639505/85073aaf-f2d0-4f9a-be8b-54b53f379f4e)

2023-07-31 10:53 UTC, RaminEsfandiari requested changes
Looks good. Just the removal of duplicate route from previous changes and happy to approve

2023-07-31 10:53 UTC, RaminEsfandiari commented on app/navigation/NavigatorForCorrectReturn.scala
> +    case PackagingSiteDetailsPage => _ => defaultCall
We might need to think about the navigation as three different variation journeys end up on this call and they may have different navigation requirements but we'll cross that bridge when we come to it.

2023-07-31 10:53 UTC, RaminEsfandiari commented on app/views/changeActivity/PackagingSiteDetailsView.scala.html
Thanks for fixing

2023-07-31 10:53 UTC, RaminEsfandiari commented on app/views/correctReturn/PackagingSiteDetailsView.scala.html
> +            }
Another way to achieve this is to send to parameters to your message, first being the size second a conditional pluraliser like "s"
See link for an example:
https://github.com/hmrc/soft-drinks-industry-levy-registration-frontend/blob/main/app/views/WarehouseDetailsView.scala.html#L28

2023-07-31 13:01 UTC, RaminEsfandiari approved these changes

2023-07-31 13:12 UTC, merged